In [1]:
from pathlib import Path
import pandas as pd

DATA_DIR = Path("../data/raw")

sales_path = DATA_DIR / "sales_train_validation.csv"
calendar_path = DATA_DIR / "calendar.csv"
prices_path = DATA_DIR / "sell_prices.csv"

print("Sales file exists:", sales_path.exists())
print("Calendar file exists:", calendar_path.exists())
print("Prices file exists:", prices_path.exists())

Sales file exists: True
Calendar file exists: True
Prices file exists: True

In [2]:
sales = pd.read_csv(sales_path)
calendar = pd.read_csv(calendar_path)
prices = pd.read_csv(prices_path)

print("Sales shape:", sales.shape)
print("Calendar shape:", calendar.shape)
print("Prices shape:", prices.shape)

Sales shape: (30490, 1919)
Calendar shape: (1969, 14)
Prices shape: (6841121, 4)

In [3]:
sales.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,3,0,1,1,1,3,0,1,1
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,2,1,1,1,0,1,1,1
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,5,4,1,0,1,3,7,2
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,1,0,1,1,2,2,2,4

In [3]:
# Inspect column data types
print("SALES DATA TYPES")
print(sales.dtypes.value_counts())

print("\nCALENDAR DATA TYPES")
print(calendar.dtypes)

print("\nPRICE DATA TYPES")
print(prices.dtypes)

SALES DATA TYPES
int64    1913
str         6
Name: count, dtype: int64

CALENDAR DATA TYPES
date              str
wm_yr_wk        int64
weekday           str
wday            int64
month           int64
year            int64
d                 str
event_name_1      str
event_type_1      str
event_name_2      str
event_type_2      str
snap_CA         int64
snap_TX         int64
snap_WI         int64
dtype: object

PRICE DATA TYPES
store_id          str
item_id           str
wm_yr_wk        int64
sell_price    float64
dtype: object

In [4]:
# Count missing values in each dataset
print("Sales missing values:", sales.isnull().sum().sum())
print("Calendar missing values:", calendar.isnull().sum().sum())
print("Prices missing values:", prices.isnull().sum().sum())

Sales missing values: 0
Calendar missing values: 7542
Prices missing values: 0

In [5]:
print("Sales duplicate rows:", sales.duplicated().sum())
print("Calendar duplicate rows:", calendar.duplicated().sum())
print("Price duplicate rows:", prices.duplicated().sum())

Sales duplicate rows: 0
Calendar duplicate rows: 0
Price duplicate rows: 0

In [7]:
# Missing values by column
missing_calendar = calendar.isnull().sum()

print(missing_calendar[missing_calendar > 0])

event_name_1    1807
event_type_1    1807
event_name_2    1964
event_type_2    1964
dtype: int64

In [6]:
# Missing value percentage
missing_percentage = (
    calendar.isnull().sum() / len(calendar) * 100
)

print(missing_percentage[missing_percentage > 0].round(2))

event_name_1    91.77
event_type_1    91.77
event_name_2    99.75
event_type_2    99.75
dtype: float64

In [9]:
print(
    "Duplicate product-store combinations:",
    sales.duplicated(
        subset=["item_id", "store_id"]
    ).sum()
)

print(
    "Duplicate calendar day IDs:",
    calendar["d"].duplicated().sum()
)

print(
    "Duplicate product-store-week prices:",
    prices.duplicated(
        subset=["store_id", "item_id", "wm_yr_wk"]
    ).sum()
)

Duplicate product-store combinations: 0
Duplicate calendar day IDs: 0
Duplicate product-store-week prices: 0

In [10]:
print("Unique products:", sales["item_id"].nunique())
print("Unique stores:", sales["store_id"].nunique())
print("Unique departments:", sales["dept_id"].nunique())
print("Unique categories:", sales["cat_id"].nunique())

print("\nStores:")
print(sales["store_id"].unique())

print("\nCategories:")
print(sales["cat_id"].unique())

Unique products: 3049
Unique stores: 10
Unique departments: 7
Unique categories: 3

Stores:
<StringArray>
['CA_1', 'CA_2', 'CA_3', 'CA_4', 'TX_1', 'TX_2', 'TX_3', 'WI_1', 'WI_2',
 'WI_3']
Length: 10, dtype: str

Categories:
<StringArray>
['HOBBIES', 'HOUSEHOLD', 'FOODS']
Length: 3, dtype: str

In [ ]:
# Convert date column into datetime
calendar["date"] = pd.to_datetime(calendar["date"])

print("First date:", calendar["date"].min())
print("Last date:", calendar["date"].max())

print("\nCalendar sample:")
print(calendar[["date", "d", "weekday", "wm_yr_wk"]].head(10))

In [7]:
# Convert date column into datetime
calendar["date"] = pd.to_datetime(calendar["date"])

print("First date:", calendar["date"].min())
print("Last date:", calendar["date"].max())

print("\nCalendar sample:")
print(calendar[["date", "d", "weekday", "wm_yr_wk"]].head(10))

First date: 2011-01-29 00:00:00
Last date: 2016-06-19 00:00:00

Calendar sample:
        date     d    weekday  wm_yr_wk
0 2011-01-29   d_1   Saturday     11101
1 2011-01-30   d_2     Sunday     11101
2 2011-01-31   d_3     Monday     11101
3 2011-02-01   d_4    Tuesday     11101
4 2011-02-02   d_5  Wednesday     11101
5 2011-02-03   d_6   Thursday     11101
6 2011-02-04   d_7     Friday     11101
7 2011-02-05   d_8   Saturday     11102
8 2011-02-06   d_9     Sunday     11102
9 2011-02-07  d_10     Monday     11102

In [8]:
print(sales["store_id"].value_counts())

store_id
CA_1    3049
CA_2    3049
CA_3    3049
CA_4    3049
TX_1    3049
TX_2    3049
TX_3    3049
WI_1    3049
WI_2    3049
WI_3    3049
Name: count, dtype: int64

In [9]:
print(sales["cat_id"].value_counts())

cat_id
FOODS        14370
HOUSEHOLD    10470
HOBBIES       5650
Name: count, dtype: int64

In [10]:
print(prices.head())

print("\nPrice range:")
print(prices["sell_price"].describe())

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

Price range:
count    6.841121e+06
mean     4.410952e+00
std      3.408814e+00
min      1.000000e-02
25%      2.180000e+00
50%      3.470000e+00
75%      5.840000e+00
max      1.073200e+02
Name: sell_price, dtype: float64

In [11]:
sales_sample = sales.head(100).copy()

print(sales_sample.shape)

(100, 1919)

In [15]:
id_columns = [
    "id",
    "item_id",
    "dept_id",
    "cat_id",
    "store_id",
    "state_id"
]

day_columns = [
    col for col in sales_sample.columns
    if col.startswith("d_")
]

sales_long = sales_sample.melt(
    id_vars=id_columns,
    value_vars=day_columns,
    var_name="day",
    value_name="units_sold"
)

In [16]:
sales_long.head(10)

,id,item_id,dept_id,cat_id,store_id,state_id,day,units_sold
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
5,HOBBIES_1_006_CA_1_validation,HOBBIES_1_006,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
6,HOBBIES_1_007_CA_1_validation,HOBBIES_1_007,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
7,HOBBIES_1_008_CA_1_validation,HOBBIES_1_008,HOBBIES_1,HOBBIES,CA_1,CA,d_1,12
8,HOBBIES_1_009_CA_1_validation,HOBBIES_1_009,HOBBIES_1,HOBBIES,CA_1,CA,d_1,2
9,HOBBIES_1_010_CA_1_validation,HOBBIES_1_010,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0

In [17]:
print("Number of day columns:", len(day_columns))
print("Expected rows:", len(sales_sample) * len(day_columns))
print("Actual rows:", len(sales_long))

Number of day columns: 1913
Expected rows: 191300
Actual rows: 191300

In [18]:
calendar["date"] = pd.to_datetime(calendar["date"])

sales_long = sales_long.merge(
    calendar[["d", "date", "wm_yr_wk"]],
    left_on="day",
    right_on="d",
    how="left"
)

sales_long.drop(columns=["d"], inplace=True)

sales_long.head()

C:\Users\SARWAR\AppData\Local\Temp\ipykernel_2596\3766090187.py:10: Pandas4Warning: The inplace keyword in DataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  sales_long.drop(columns=["d"], inplace=True)

,id,item_id,dept_id,cat_id,store_id,state_id,day,units_sold,date,wm_yr_wk
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101

In [19]:
print("Rows:", sales_long.shape[0])
print("Missing dates:", sales_long["date"].isna().sum())
print("Missing week numbers:", sales_long["wm_yr_wk"].isna().sum())

Rows: 191300
Missing dates: 0
Missing week numbers: 0

In [23]:
prices.head(10)

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26
5     CA_1  HOBBIES_1_001     11330        8.26
6     CA_1  HOBBIES_1_001     11331        8.26
7     CA_1  HOBBIES_1_001     11332        8.26
8     CA_1  HOBBIES_1_001     11333        8.26
9     CA_1  HOBBIES_1_001     11334        8.26

In [24]:
sales_long = sales_long.merge(
    prices,
    on=["item_id", "store_id", "wm_yr_wk"],
    how="left"
)

sales_long.head()

,id,item_id,dept_id,cat_id,store_id,state_id,day,units_sold,date,wm_yr_wk,sell_price
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,NaN

In [41]:
print("Shape:", sales_long.shape)

print("\nMissing values:")
print(sales_long.isna().sum())

print("\nData types:")
sales_long.info()

Shape: (191300, 11)

Missing values:
id                0
item_id           0
dept_id           0
cat_id            0
store_id          0
state_id          0
day               0
units_sold        0
date              0
wm_yr_wk          0
sell_price    30940
dtype: int64

Data types:
<class 'pandas.DataFrame'>
RangeIndex: 191300 entries, 0 to 191299
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id          191300 non-null  str
 1   item_id     191300 non-null  str
 2   dept_id     191300 non-null  str
 3   cat_id      191300 non-null  str
 4   store_id    191300 non-null  str
 5   state_id    191300 non-null  str
 6   day         191300 non-null  str
 7   units_sold  191300 non-null  int64
 8   date        191300 non-null  datetime64[us]
 9   wm_yr_wk    191300 non-null  int64
 10  sell_price  160360 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(2), str(7)
memory usage: 16.1 MB

In [42]:
missing_price_sales = sales_long[
    sales_long["sell_price"].isna()
]

print("Total missing-price records:",
      len(missing_price_sales))

print("Records with sales > 0:",
      (missing_price_sales["units_sold"] > 0).sum())

print("Records with sales = 0:",
      (missing_price_sales["units_sold"] == 0).sum())

Total missing-price records: 30940
Records with sales > 0: 0
Records with sales = 0: 30940

In [43]:
contradictions = sales_long[
    sales_long["sell_price"].isna() &
    (sales_long["units_sold"] > 0)
]

contradictions[
    ["item_id", "store_id", "date", "units_sold", "wm_yr_wk"]
].head(20)

Empty DataFrame
Columns: [item_id, store_id, date, units_sold, wm_yr_wk]
Index: []

In [44]:
product_demand = (
    sales_long
    .groupby("item_id")["units_sold"]
    .sum()
    .sort_values(ascending=False)
)

product_demand.head(10)

item_id
HOBBIES_1_048    13867
HOBBIES_1_008    13830
HOBBIES_1_015    11602
HOBBIES_1_032    10642
HOBBIES_1_016    10575
HOBBIES_1_067     9926
HOBBIES_1_019     9052
HOBBIES_1_103     7941
HOBBIES_1_080     6567
HOBBIES_1_043     6290
Name: units_sold, dtype: int64

In [45]:
print("Total units sold:", sales_long["units_sold"].sum())
print("Number of products:", sales_long["item_id"].nunique())
print("Average units sold per product:",
      product_demand.mean())

Total units sold: 202130
Number of products: 100
Average units sold per product: 2021.3

In [46]:
zero_sales = (
    sales_long
    .groupby("item_id")["units_sold"]
    .apply(lambda x: (x == 0).sum())
    .sort_values(ascending=False)
)

zero_sales.head(10)

item_id
HOBBIES_1_026    1894
HOBBIES_1_018    1834
HOBBIES_1_062    1827
HOBBIES_1_053    1813
HOBBIES_1_052    1800
HOBBIES_1_011    1784
HOBBIES_1_070    1767
HOBBIES_1_065    1760
HOBBIES_1_054    1744
HOBBIES_1_039    1743
Name: units_sold, dtype: int64

In [ ]:
sales_full = pd.read_csv(sales_path)

print("Shape:", sales_full.shape)
print("Categories:")
print(sales_full["cat_id"].value_counts())

print("\nUnique products:", sales_full["item_id"].nunique())
print("Unique stores:", sales_full["store_id"].nunique())

In [50]:
sales_full = pd.read_csv(sales_path)

print("Shape:", sales_full.shape)
print("Categories:")
print(sales_full["cat_id"].value_counts())

print("\nUnique products:", sales_full["item_id"].nunique())
print("Unique stores:", sales_full["store_id"].nunique())

Shape: (30490, 1919)
Categories:
cat_id
FOODS        14370
HOUSEHOLD    10470
HOBBIES       5650
Name: count, dtype: int64

Unique products: 3049
Unique stores: 10

In [51]:
sales_full.groupby("cat_id")["item_id"].nunique()

cat_id
FOODS        1437
HOBBIES       565
HOUSEHOLD    1047
Name: item_id, dtype: int64

In [52]:
print(
    "Sales dataset memory:",
    round(sales_full.memory_usage(deep=True).sum() / (1024**2), 2),
    "MB"
)

Sales dataset memory: 456.78 MB

In [53]:

# Identifier / metadata columns
id_columns = [
    "id", "item_id", "dept_id",
    "cat_id", "store_id", "state_id"
]

# Daily sales columns
day_columns = [
    col for col in sales_full.columns
    if col.startswith("d_")
]

print("Metadata columns:", len(id_columns))
print("Daily sales columns:", len(day_columns))

print("First 5 days:", day_columns[:5])
print("Last 5 days:", day_columns[-5:])

print("Total historical days:", len(day_columns))

Metadata columns: 6
Daily sales columns: 1913
First 5 days: ['d_1', 'd_2', 'd_3', 'd_4', 'd_5']
Last 5 days: ['d_1909', 'd_1910', 'd_1911', 'd_1912', 'd_1913']
Total historical days: 1913

In [54]:

# Total units sold across all 1913 days
category_sales = (
    sales_full.groupby("cat_id")[day_columns]
    .sum()
    .sum(axis=1)
    .sort_values(ascending=False)
)

print(category_sales)

cat_id
FOODS        45089939
HOUSEHOLD    14480670
HOBBIES       6124800
dtype: int64